services:
  website:
    build: ./website
    ports:
      - 8000:8000

  database:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_PASSWORD=/run/secrets/db_password
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - db_password

secrets:
  db_password:
    file: secrets/db_password.txt

volumes:
  db-data: {}
