services:
  website:
    build: ./website
    environment:
      BW_API_URL: /run/secrets/bw_api_url
      BW_IDENTITY_URL: /run/secrets/bw_identity_url
      BW_ACCESS_TOKEN: /run/secrets/bw_access_token
      POSTGRES_PASSWORD: /run/secrets/db_password
    expose:
      - 8000
    secrets:
      - bw_api_url
      - bw_identity_url
      - bw_access_token
      - db_password
    networks:
      - frontend
      - backend

  database:
    build: ./database
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - db_password
    networks:
      - backend

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    secrets:
      - ssl_cert
      - ssl_key
    networks:
      - frontend

secrets:
  bw_api_url:
    file: secrets/bw_api_url.txt
  bw_identity_url:
    file: secrets/bw_identity_url.txt
  bw_access_token:
    file: secrets/bw_access_token.txt
  db_password:
    file: secrets/db_password.txt
  ssl_cert:
    file: secrets/cert.pem
  ssl_key:
    file: secrets/key.pem

volumes:
  db-data: {}

networks:
  frontend:
  backend:
